### ISSUE TITLE
error with bam2bigwig

### ISSUE THREAD

**Issue by verne91** [lpryszcz/bin#1]
Hello,

When I run the bam2bigwig, I came across a problem.

`/tmp/pybedtools.0lJ1Nt.tmp is not case-sensitive sorted at line 1857598.  Please use "sort -k1,1 -k2,2n" with LC_COLLATE=C,  or bedSort and try again.
# Time elapsed: 0:00:26.312967`

Any idea?

**Comment by lpryszcz** [comment]
is your bam file sorted by coordinate using `samtools sort`?

**Comment by verne91** [comment]
Yes

**Comment by lpryszcz** [comment]
Can you share your bam / fasta index (.fai)? Or at least the part that causes an error? 
Otherwise I cannot really see what causes the problem.
