### ISSUE TITLE
rename_contigs.py hangs

### ISSUE THREAD

**Issue by ReneKat** [lpryszcz/bin#2]
Hello there,
Thank you for making these scripts available to the public! I know a little python and am learning more from your scripts. 
I am running rename_contigs.py and I noticed a typo in line 10 "contig". Anyways, after that correction though, the script is still hanging and I don't know enough yet about python to understand the code :( 
Thank you for your time and talents.
Best Regards,
Rene

**Comment by lpryszcz** [comment]
Thanks for the report. I've rewritten it from the scratch - it should run smoothly now :)
